import dalPhotoSrc from "~/assets/images/recipes/dal.png";
import risottoPhotoSrc from "~/assets/images/recipes/risotto.png";
import sheetpanPhotoSrc from "~/assets/images/recipes/sheetpan.png";
import skewersPhotoSrc from "~/assets/images/recipes/skewers.png";
import tacosPhotoSrc from "~/assets/images/recipes/tacos.png";
import type { Recipe, RecipeAuthor, RecipeTagCategory, ScannedRecipe } from "~/core/recipes/RecipeTypes";

/**
 * Placeholder content for the recipe views.
 *
 * The app has no recipe service yet, so routes and stories both read from here.
 * Replacing it with a loader is a one-line change in each route hook.
 */

/** Tags offered as chips before the cook opens the full community catalogue. */
export const SuggestedTags = ["vegetarian", "meat", "fish", "bbq", "quick", "cheap", "expensive", "comfort"];

export const SampleAuthorMe: RecipeAuthor = {
  id: "me",
  name: "Petter",
  handle: "@petter",
  avatarUrl: null,
  color: "oklch(0.62 0.195 253.8)",
};

export const SampleAuthorElin: RecipeAuthor = {
  id: "p1",
  name: "Elin Håkansson",
  handle: "@elin",
  avatarUrl: null,
  color: "oklch(0.62 0.195 253.8)",
};

export const SampleAuthorMarcus: RecipeAuthor = {
  id: "p2",
  name: "Marcus Reid",
  handle: "@marcus",
  avatarUrl: null,
  color: "oklch(0.60 0.20 25)",
};

export const SampleAuthorPriya: RecipeAuthor = {
  id: "p3",
  name: "Priya Raman",
  handle: "@priya",
  avatarUrl: null,
  color: "oklch(0.60 0.14 155)",
};

export const SampleAuthorTomas: RecipeAuthor = {
  id: "p4",
  name: "Tomas Lind",
  handle: "@tomas",
  avatarUrl: null,
  color: "oklch(0.65 0.15 65)",
};

export const SampleAuthorSara: RecipeAuthor = {
  id: "p5",
  name: "Sara Okafor",
  handle: "@sara",
  avatarUrl: null,
  color: "oklch(0.55 0.19 300)",
};

export const SampleRecipes: Recipe[] = [
  {
    id: "r1",
    title: "Red lentil dal",
    tags: ["vegetarian", "cheap", "quick"],
    servings: 4,
    timeMinutes: 30,
    photoUrl: dalPhotoSrc,
    author: SampleAuthorMe,
    isSaved: true,
    ingredients: [
      { quantity: 300, unit: "g", item: "Red lentils" },
      { quantity: 1, unit: "tin", item: "Chopped tomatoes" },
      { quantity: 2, unit: "tbsp", item: "Curry powder" },
      { quantity: 1, unit: "", item: "Onion" },
      { quantity: 400, unit: "ml", item: "Coconut milk" },
    ],
    steps: [
      "Soften the onion in oil for five minutes.",
      "Add curry powder, then lentils, tomatoes and coconut milk.",
      "Simmer 20 minutes until the lentils collapse.",
      "Season and serve with rice or flatbread.",
    ],
  },
  {
    id: "r2",
    title: "Lamb skewers on the grill",
    tags: ["meat", "bbq", "expensive"],
    servings: 4,
    timeMinutes: 45,
    photoUrl: skewersPhotoSrc,
    author: SampleAuthorMe,
    isSaved: true,
    ingredients: [
      { quantity: 800, unit: "g", item: "Lamb shoulder, cubed" },
      { quantity: 3, unit: "cloves", item: "Garlic" },
      { quantity: 2, unit: "tbsp", item: "Olive oil" },
      { quantity: 1, unit: "tsp", item: "Ground cumin" },
      { quantity: 2, unit: "", item: "Red onion" },
    ],
    steps: [
      "Mix oil, crushed garlic and cumin, coat the lamb and rest 30 minutes.",
      "Thread onto skewers with wedges of red onion.",
      "Grill over direct heat, turning every two minutes.",
      "Rest five minutes before serving.",
    ],
  },
  {
    id: "r3",
    title: "Mushroom risotto",
    tags: ["vegetarian", "comfort"],
    servings: 4,
    timeMinutes: 40,
    photoUrl: risottoPhotoSrc,
    author: SampleAuthorMe,
    isSaved: true,
    ingredients: [
      { quantity: 320, unit: "g", item: "Arborio rice" },
      { quantity: 400, unit: "g", item: "Mixed mushrooms" },
      { quantity: 1.2, unit: "l", item: "Vegetable stock" },
      { quantity: 60, unit: "g", item: "Parmesan" },
      { quantity: 40, unit: "g", item: "Butter" },
    ],
    steps: [
      "Fry the mushrooms hard in batches, set aside.",
      "Toast the rice in butter, then add stock a ladle at a time.",
      "After 18 minutes fold the mushrooms back in.",
      "Finish off the heat with butter and parmesan.",
    ],
  },
  {
    id: "r4",
    title: "Sheet-pan chicken and root veg",
    tags: ["meat", "cheap", "sheet-pan"],
    servings: 4,
    timeMinutes: 55,
    photoUrl: sheetpanPhotoSrc,
    author: SampleAuthorMe,
    isSaved: true,
    ingredients: [
      { quantity: 8, unit: "", item: "Chicken thighs" },
      { quantity: 600, unit: "g", item: "Carrots and parsnips" },
      { quantity: 2, unit: "tbsp", item: "Olive oil" },
      { quantity: 1, unit: "tbsp", item: "Dried thyme" },
      { quantity: 1, unit: "", item: "Lemon" },
    ],
    steps: [
      "Heat the oven to 220C.",
      "Toss the veg in oil and thyme, spread on a tray.",
      "Sit the chicken on top, skin up, and roast 45 minutes.",
      "Squeeze over lemon before serving.",
    ],
  },
  {
    id: "r5",
    title: "Salmon tacos",
    tags: ["fish", "quick"],
    servings: 4,
    timeMinutes: 25,
    photoUrl: tacosPhotoSrc,
    author: SampleAuthorMe,
    isSaved: true,
    ingredients: [
      { quantity: 600, unit: "g", item: "Salmon fillet" },
      { quantity: 8, unit: "", item: "Small tortillas" },
      { quantity: 200, unit: "g", item: "White cabbage" },
      { quantity: 150, unit: "g", item: "Yoghurt" },
      { quantity: 1, unit: "", item: "Lime" },
    ],
    steps: [
      "Rub the salmon with paprika and roast 12 minutes.",
      "Shred the cabbage and dress with lime.",
      "Stir lime zest through the yoghurt.",
      "Flake the fish into warm tortillas and pile on the slaw.",
    ],
  },
  {
    id: "r6",
    title: "Halloumi and chickpea salad",
    tags: ["vegetarian", "quick"],
    servings: 2,
    timeMinutes: 20,
    photoUrl: null,
    author: SampleAuthorMe,
    isSaved: true,
    ingredients: [
      { quantity: 250, unit: "g", item: "Halloumi" },
      { quantity: 1, unit: "tin", item: "Chickpeas" },
      { quantity: 150, unit: "g", item: "Cherry tomatoes" },
      { quantity: 2, unit: "tbsp", item: "Olive oil" },
      { quantity: 1, unit: "handful", item: "Mint" },
    ],
    steps: [
      "Fry thick slices of halloumi until deeply golden.",
      "Warm the chickpeas with oil and halved tomatoes.",
      "Combine, tear over mint and finish with lemon.",
    ],
  },
  {
    id: "c1",
    title: "Paneer butter masala",
    tags: ["vegetarian", "comfort"],
    servings: 4,
    timeMinutes: 45,
    daysAgo: 3,
    photoUrl: risottoPhotoSrc,
    author: SampleAuthorPriya,
    isSaved: false,
    ingredients: [
      { quantity: 400, unit: "g", item: "Paneer" },
      { quantity: 1, unit: "tin", item: "Chopped tomatoes" },
      { quantity: 100, unit: "ml", item: "Double cream" },
      { quantity: 2, unit: "tbsp", item: "Butter" },
      { quantity: 1, unit: "tbsp", item: "Garam masala" },
    ],
    steps: [
      "Fry the paneer in butter until it colours, set aside.",
      "Cook tomatoes with garam masala until they darken and split.",
      "Blend smooth, add cream, return the paneer and warm through.",
    ],
  },
  {
    id: "c2",
    title: "Chana masala",
    tags: ["vegetarian", "cheap", "quick"],
    servings: 4,
    timeMinutes: 30,
    daysAgo: 9,
    photoUrl: null,
    author: SampleAuthorPriya,
    isSaved: false,
    ingredients: [
      { quantity: 2, unit: "tins", item: "Chickpeas" },
      { quantity: 1, unit: "", item: "Onion" },
      { quantity: 2, unit: "tsp", item: "Ground cumin" },
      { quantity: 1, unit: "tin", item: "Chopped tomatoes" },
      { quantity: 1, unit: "", item: "Lemon" },
    ],
    steps: [
      "Brown the onion properly, ten minutes, not five.",
      "Add cumin, tomatoes and chickpeas, simmer 15 minutes.",
      "Crush a few chickpeas to thicken it, finish with lemon.",
    ],
  },
  {
    id: "c3",
    title: "Coconut sambar",
    tags: ["vegetarian", "cheap"],
    servings: 4,
    timeMinutes: 35,
    daysAgo: 21,
    photoUrl: null,
    author: SampleAuthorPriya,
    isSaved: false,
    ingredients: [
      { quantity: 200, unit: "g", item: "Toor dal" },
      { quantity: 300, unit: "g", item: "Mixed vegetables" },
      { quantity: 50, unit: "g", item: "Grated coconut" },
      { quantity: 1, unit: "tbsp", item: "Tamarind paste" },
    ],
    steps: [
      "Boil the dal until it breaks down completely.",
      "Add vegetables and tamarind, cook until just tender.",
      "Stir in coconut off the heat and temper mustard seeds over the top.",
    ],
  },
  {
    id: "c4",
    title: "Smoked pork shoulder",
    tags: ["meat", "bbq", "expensive"],
    servings: 8,
    timeMinutes: 240,
    daysAgo: 5,
    photoUrl: null,
    author: SampleAuthorMarcus,
    isSaved: false,
    ingredients: [
      { quantity: 2.5, unit: "kg", item: "Pork shoulder" },
      { quantity: 3, unit: "tbsp", item: "Paprika rub" },
      { quantity: 200, unit: "ml", item: "Cider vinegar" },
    ],
    steps: [
      "Rub the shoulder the night before and leave it uncovered in the fridge.",
      "Smoke at 110C until the bark sets, about four hours.",
      "Wrap, push to 95C internal, then rest a full hour before pulling.",
    ],
  },
  {
    id: "c5",
    title: "Harissa chicken thighs",
    tags: ["meat", "bbq", "quick"],
    servings: 4,
    timeMinutes: 30,
    daysAgo: 2,
    photoUrl: skewersPhotoSrc,
    author: SampleAuthorMarcus,
    isSaved: false,
    ingredients: [
      { quantity: 8, unit: "", item: "Chicken thighs" },
      { quantity: 3, unit: "tbsp", item: "Harissa" },
      { quantity: 150, unit: "g", item: "Yoghurt" },
      { quantity: 1, unit: "", item: "Lemon" },
    ],
    steps: [
      "Mix harissa and half the yoghurt, coat the thighs.",
      "Grill skin-side down over medium heat until crisp, then flip.",
      "Serve with the rest of the yoghurt and a squeeze of lemon.",
    ],
  },
  {
    id: "c6",
    title: "Beef short rib braise",
    tags: ["meat", "comfort", "expensive"],
    servings: 4,
    timeMinutes: 180,
    daysAgo: 14,
    photoUrl: null,
    author: SampleAuthorMarcus,
    isSaved: false,
    ingredients: [
      { quantity: 1.5, unit: "kg", item: "Beef short rib" },
      { quantity: 500, unit: "ml", item: "Red wine" },
      { quantity: 2, unit: "", item: "Carrots" },
      { quantity: 1, unit: "", item: "Onion" },
    ],
    steps: [
      "Brown the ribs hard on every side.",
      "Soften the vegetables, deglaze with the wine, reduce by half.",
      "Cover and braise at 150C for three hours until it gives to a spoon.",
    ],
  },
  {
    id: "c7",
    title: "Cod with brown butter",
    tags: ["fish", "quick"],
    servings: 4,
    timeMinutes: 25,
    daysAgo: 1,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 700, unit: "g", item: "Cod loin" },
      { quantity: 80, unit: "g", item: "Butter" },
      { quantity: 2, unit: "tbsp", item: "Capers" },
      { quantity: 1, unit: "", item: "Lemon" },
    ],
    steps: [
      "Salt the cod 15 minutes ahead and pat it dry.",
      "Pan-fry in a little oil, four minutes a side, then rest.",
      "Brown the butter, drop in capers and lemon, pour over.",
    ],
  },
  {
    id: "c8",
    title: "Mussels in cider",
    tags: ["fish", "cheap", "quick"],
    servings: 4,
    timeMinutes: 25,
    daysAgo: 6,
    photoUrl: tacosPhotoSrc,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 2, unit: "kg", item: "Mussels" },
      { quantity: 330, unit: "ml", item: "Dry cider" },
      { quantity: 150, unit: "ml", item: "Double cream" },
      { quantity: 1, unit: "bunch", item: "Parsley" },
    ],
    steps: [
      "Clean the mussels and discard any that stay open.",
      "Steam in the cider with a lid on, four minutes, shaking the pan.",
      "Lift them out, reduce the liquor, stir in cream and parsley.",
    ],
  },
  {
    id: "c9",
    title: "Fish pie",
    tags: ["fish", "comfort"],
    servings: 6,
    timeMinutes: 60,
    daysAgo: 18,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 800, unit: "g", item: "Mixed fish" },
      { quantity: 1, unit: "kg", item: "Potatoes" },
      { quantity: 600, unit: "ml", item: "Milk" },
      { quantity: 50, unit: "g", item: "Flour" },
      { quantity: 50, unit: "g", item: "Butter" },
    ],
    steps: [
      "Poach the fish in the milk, then lift it out and flake it.",
      "Build a white sauce from the poaching milk, butter and flour.",
      "Fold the fish in, top with mash, bake 30 minutes at 200C.",
    ],
  },
  {
    id: "c10",
    title: "Sausage and lentil stew",
    tags: ["meat", "cheap", "comfort"],
    servings: 4,
    timeMinutes: 45,
    daysAgo: 4,
    photoUrl: null,
    author: SampleAuthorTomas,
    isSaved: false,
    ingredients: [
      { quantity: 6, unit: "", item: "Pork sausages" },
      { quantity: 250, unit: "g", item: "Puy lentils" },
      { quantity: 1, unit: "tin", item: "Chopped tomatoes" },
      { quantity: 2, unit: "", item: "Carrots" },
    ],
    steps: [
      "Brown the sausages whole, then cut them into thick coins.",
      "Sweat the carrots, add lentils, tomatoes and 600ml water.",
      "Simmer 30 minutes, return the sausage, season hard.",
    ],
  },
  {
    id: "c11",
    title: "Pasta with tuna and capers",
    tags: ["fish", "cheap", "quick"],
    servings: 4,
    timeMinutes: 20,
    daysAgo: 8,
    photoUrl: null,
    author: SampleAuthorTomas,
    isSaved: false,
    ingredients: [
      { quantity: 400, unit: "g", item: "Spaghetti" },
      { quantity: 2, unit: "tins", item: "Tuna in oil" },
      { quantity: 2, unit: "tbsp", item: "Capers" },
      { quantity: 1, unit: "", item: "Lemon" },
      { quantity: 1, unit: "clove", item: "Garlic" },
    ],
    steps: [
      "Cook the pasta one minute short of the packet time.",
      "Warm tuna, its oil, garlic and capers in a wide pan.",
      "Toss with pasta water until glossy, finish with lemon zest.",
    ],
  },
  {
    id: "c12",
    title: "Big-batch chilli",
    tags: ["meat", "cheap", "comfort"],
    servings: 8,
    timeMinutes: 90,
    daysAgo: 7,
    photoUrl: dalPhotoSrc,
    author: SampleAuthorSara,
    isSaved: false,
    ingredients: [
      { quantity: 1, unit: "kg", item: "Beef mince" },
      { quantity: 2, unit: "tins", item: "Kidney beans" },
      { quantity: 2, unit: "tins", item: "Chopped tomatoes" },
      { quantity: 2, unit: "tbsp", item: "Chilli powder" },
      { quantity: 20, unit: "g", item: "Dark chocolate" },
    ],
    steps: [
      "Brown the mince in batches so it fries rather than steams.",
      "Add spices, tomatoes and beans, simmer an hour uncovered.",
      "Melt the chocolate in at the end. Freezes in four portions.",
    ],
  },
  {
    id: "c13",
    title: "Roast veg traybake with feta",
    tags: ["vegetarian", "cheap"],
    servings: 4,
    timeMinutes: 45,
    daysAgo: 11,
    photoUrl: null,
    author: SampleAuthorSara,
    isSaved: false,
    ingredients: [
      { quantity: 800, unit: "g", item: "Root vegetables" },
      { quantity: 200, unit: "g", item: "Feta" },
      { quantity: 3, unit: "tbsp", item: "Olive oil" },
      { quantity: 1, unit: "tbsp", item: "Honey" },
    ],
    steps: [
      "Cut everything the same size, toss in oil, roast at 220C.",
      "After 30 minutes crumble the feta over and drizzle honey.",
      "Back in for ten minutes until the feta takes colour.",
    ],
  },
  {
    id: "c14",
    title: "Miso aubergine rice bowls",
    tags: ["vegetarian", "quick"],
    servings: 4,
    timeMinutes: 30,
    daysAgo: 16,
    photoUrl: null,
    author: SampleAuthorSara,
    isSaved: false,
    ingredients: [
      { quantity: 3, unit: "", item: "Aubergines" },
      { quantity: 3, unit: "tbsp", item: "White miso" },
      { quantity: 1, unit: "tbsp", item: "Mirin" },
      { quantity: 300, unit: "g", item: "Short-grain rice" },
    ],
    steps: [
      "Halve the aubergines, score them, roast cut-side down 20 minutes.",
      "Mix miso and mirin, brush on, grill until it blisters.",
      "Serve on rice with the pan juices spooned over.",
    ],
  },
  {
    id: "c15",
    title: "One-tray roast chicken",
    tags: ["meat", "comfort"],
    servings: 4,
    timeMinutes: 75,
    daysAgo: 10,
    photoUrl: sheetpanPhotoSrc,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 1.4, unit: "kg", item: "Whole chicken" },
      { quantity: 800, unit: "g", item: "Potatoes" },
      { quantity: 2, unit: "", item: "Lemons" },
      { quantity: 3, unit: "sprigs", item: "Thyme" },
    ],
    steps: [
      "Halve the potatoes and toss them in oil in a deep tray.",
      "Sit the chicken on top with lemon and thyme, roast 70 minutes at 200C.",
      "Rest 15 minutes and spoon the tray juices back over the potatoes.",
    ],
  },
  {
    id: "c16",
    title: "Spaghetti with anchovy and chilli",
    tags: ["fish", "cheap", "quick"],
    servings: 4,
    timeMinutes: 20,
    daysAgo: 12,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 400, unit: "g", item: "Spaghetti" },
      { quantity: 8, unit: "", item: "Anchovy fillets" },
      { quantity: 1, unit: "", item: "Red chilli" },
      { quantity: 2, unit: "cloves", item: "Garlic" },
      { quantity: 60, unit: "g", item: "Breadcrumbs" },
    ],
    steps: [
      "Toast the breadcrumbs in oil until golden, set aside.",
      "Melt the anchovies into oil with garlic and chilli.",
      "Toss with the pasta and a ladle of its water, top with crumbs.",
    ],
  },
  {
    id: "c17",
    title: "Salmon with dill potatoes",
    tags: ["fish"],
    servings: 4,
    timeMinutes: 35,
    daysAgo: 15,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 700, unit: "g", item: "Salmon fillet" },
      { quantity: 900, unit: "g", item: "New potatoes" },
      { quantity: 1, unit: "bunch", item: "Dill" },
      { quantity: 150, unit: "g", item: "Crème fraîche" },
    ],
    steps: [
      "Boil the potatoes, drain and dress them warm with butter and dill.",
      "Roast the salmon at 180C for 14 minutes, no longer.",
      "Stir dill and lemon into the crème fraîche and serve alongside.",
    ],
  },
  {
    id: "c18",
    title: "Prawn and fennel risotto",
    tags: ["fish", "expensive"],
    servings: 4,
    timeMinutes: 40,
    daysAgo: 17,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 300, unit: "g", item: "Arborio rice" },
      { quantity: 400, unit: "g", item: "Raw prawns" },
      { quantity: 1, unit: "", item: "Fennel bulb" },
      { quantity: 1, unit: "l", item: "Fish stock" },
      { quantity: 150, unit: "ml", item: "White wine" },
    ],
    steps: [
      "Soften the fennel slowly, then toast the rice in it.",
      "Add wine, then stock a ladle at a time for 18 minutes.",
      "Stir the prawns through at the end and let the heat cook them.",
    ],
  },
  {
    id: "c19",
    title: "Leek and potato soup",
    tags: ["vegetarian", "cheap"],
    servings: 4,
    timeMinutes: 35,
    daysAgo: 20,
    photoUrl: dalPhotoSrc,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 3, unit: "", item: "Leeks" },
      { quantity: 600, unit: "g", item: "Potatoes" },
      { quantity: 1, unit: "l", item: "Vegetable stock" },
      { quantity: 100, unit: "ml", item: "Double cream" },
    ],
    steps: [
      "Sweat the sliced leeks in butter without colouring them.",
      "Add potatoes and stock, simmer 20 minutes.",
      "Blend, loosen with cream, season more than feels right.",
    ],
  },
  {
    id: "c20",
    title: "Baked cod with tomatoes and olives",
    tags: ["fish", "quick"],
    servings: 4,
    timeMinutes: 30,
    daysAgo: 22,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 700, unit: "g", item: "Cod loin" },
      { quantity: 400, unit: "g", item: "Cherry tomatoes" },
      { quantity: 100, unit: "g", item: "Black olives" },
      { quantity: 3, unit: "tbsp", item: "Olive oil" },
    ],
    steps: [
      "Roast tomatoes and olives at 200C until they collapse.",
      "Nestle the cod in, season, back in for 12 minutes.",
      "Spoon the oily juices over each piece before serving.",
    ],
  },
  {
    id: "c21",
    title: "Pork chops with apple",
    tags: ["meat", "quick"],
    servings: 4,
    timeMinutes: 30,
    daysAgo: 24,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 4, unit: "", item: "Pork chops" },
      { quantity: 2, unit: "", item: "Apples" },
      { quantity: 1, unit: "tbsp", item: "Wholegrain mustard" },
      { quantity: 100, unit: "ml", item: "Cider" },
    ],
    steps: [
      "Render the fat edge first, standing the chops on their side.",
      "Fry 4 minutes a side, rest them on a warm plate.",
      "Cook apple wedges in the pan, deglaze with cider and mustard.",
    ],
  },
  {
    id: "c22",
    title: "Mushroom and tarragon pasta",
    tags: ["vegetarian", "quick"],
    servings: 4,
    timeMinutes: 25,
    daysAgo: 26,
    photoUrl: risottoPhotoSrc,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 400, unit: "g", item: "Tagliatelle" },
      { quantity: 500, unit: "g", item: "Mixed mushrooms" },
      { quantity: 150, unit: "ml", item: "Double cream" },
      { quantity: 1, unit: "small bunch", item: "Tarragon" },
    ],
    steps: [
      "Fry the mushrooms in a hot dry pan first, then add butter.",
      "Add cream and tarragon, reduce for two minutes.",
      "Toss with the pasta and plenty of black pepper.",
    ],
  },
  {
    id: "c23",
    title: "Lamb meatballs with couscous",
    tags: ["meat"],
    servings: 4,
    timeMinutes: 40,
    daysAgo: 28,
    photoUrl: skewersPhotoSrc,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 600, unit: "g", item: "Lamb mince" },
      { quantity: 2, unit: "tsp", item: "Ground cumin" },
      { quantity: 250, unit: "g", item: "Couscous" },
      { quantity: 1, unit: "tin", item: "Chopped tomatoes" },
      { quantity: 150, unit: "g", item: "Yoghurt" },
    ],
    steps: [
      "Mix the mince with cumin and salt, roll into 20 balls.",
      "Brown them, then simmer in the tomatoes for 20 minutes.",
      "Steam the couscous and serve with cold yoghurt over the top.",
    ],
  },
  {
    id: "c24",
    title: "Thai green curry with white fish",
    tags: ["fish", "quick"],
    servings: 4,
    timeMinutes: 25,
    daysAgo: 30,
    photoUrl: tacosPhotoSrc,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 700, unit: "g", item: "White fish" },
      { quantity: 3, unit: "tbsp", item: "Green curry paste" },
      { quantity: 400, unit: "ml", item: "Coconut milk" },
      { quantity: 200, unit: "g", item: "Green beans" },
    ],
    steps: [
      "Fry the paste in a spoon of coconut cream until it splits.",
      "Add the rest of the milk and the beans, simmer 5 minutes.",
      "Slide the fish in and poach gently for 6 minutes.",
    ],
  },
  {
    id: "c25",
    title: "Halloumi and lentil salad",
    tags: ["vegetarian", "quick"],
    servings: 4,
    timeMinutes: 25,
    daysAgo: 32,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 400, unit: "g", item: "Halloumi" },
      { quantity: 250, unit: "g", item: "Puy lentils" },
      { quantity: 1, unit: "", item: "Cucumber" },
      { quantity: 2, unit: "tbsp", item: "Red wine vinegar" },
    ],
    steps: [
      "Cook the lentils and dress them while still warm.",
      "Fry the halloumi in a dry pan until deeply coloured.",
      "Fold in chopped cucumber and herbs, top with the cheese.",
    ],
  },
  {
    id: "c26",
    title: "Slow beef ragu",
    tags: ["meat", "comfort"],
    servings: 6,
    timeMinutes: 180,
    daysAgo: 34,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 1, unit: "kg", item: "Beef shin" },
      { quantity: 2, unit: "tins", item: "Chopped tomatoes" },
      { quantity: 200, unit: "ml", item: "Red wine" },
      { quantity: 1, unit: "", item: "Onion" },
      { quantity: 2, unit: "", item: "Carrots" },
    ],
    steps: [
      "Brown the beef in large pieces, take your time.",
      "Soften the vegetables, add wine and tomatoes, cover.",
      "Three hours at 150C, then shred it into the sauce.",
    ],
  },
  {
    id: "c27",
    title: "Tuna and white bean salad",
    tags: ["fish", "cheap", "quick"],
    servings: 4,
    timeMinutes: 15,
    daysAgo: 36,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 2, unit: "tins", item: "Tuna in oil" },
      { quantity: 2, unit: "tins", item: "Cannellini beans" },
      { quantity: 1, unit: "", item: "Red onion" },
      { quantity: 1, unit: "", item: "Lemon" },
    ],
    steps: [
      "Slice the onion thin and soak it in lemon juice for ten minutes.",
      "Fold beans, tuna and its oil together without mashing them.",
      "Add the onion with its juice, plenty of parsley, done.",
    ],
  },
  {
    id: "c28",
    title: "Shakshuka",
    tags: ["vegetarian", "cheap", "quick"],
    servings: 4,
    timeMinutes: 30,
    daysAgo: 38,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 2, unit: "tins", item: "Chopped tomatoes" },
      { quantity: 2, unit: "", item: "Red peppers" },
      { quantity: 8, unit: "", item: "Eggs" },
      { quantity: 2, unit: "tsp", item: "Ground cumin" },
    ],
    steps: [
      "Cook the peppers down with cumin until sweet.",
      "Add tomatoes and reduce until the spoon leaves a trail.",
      "Make eight wells, crack in the eggs, lid on for 6 minutes.",
    ],
  },
  {
    id: "c29",
    title: "Crisp-skin sea bass",
    tags: ["fish", "quick", "expensive"],
    servings: 4,
    timeMinutes: 20,
    daysAgo: 40,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 8, unit: "", item: "Sea bass fillets" },
      { quantity: 300, unit: "g", item: "Spinach" },
      { quantity: 40, unit: "g", item: "Butter" },
      { quantity: 1, unit: "", item: "Lemon" },
    ],
    steps: [
      "Dry the skin thoroughly and salt it just before cooking.",
      "Skin-side down in a hot pan, press flat, 3 minutes, then off the heat.",
      "Wilt the spinach in butter and serve the fish on top.",
    ],
  },
  {
    id: "c30",
    title: "Chicken and leek pie",
    tags: ["meat", "comfort"],
    servings: 6,
    timeMinutes: 70,
    daysAgo: 42,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 700, unit: "g", item: "Chicken thighs" },
      { quantity: 3, unit: "", item: "Leeks" },
      { quantity: 320, unit: "g", item: "Puff pastry" },
      { quantity: 300, unit: "ml", item: "Milk" },
      { quantity: 40, unit: "g", item: "Flour" },
    ],
    steps: [
      "Poach the thighs, keep the liquid, shred the meat.",
      "Sweat leeks, make a sauce with flour, milk and the poaching liquid.",
      "Fill, lid with pastry, bake 35 minutes at 200C.",
    ],
  },
  {
    id: "c31",
    title: "Cauliflower cheese with bacon",
    tags: ["comfort", "cheap"],
    servings: 4,
    timeMinutes: 45,
    daysAgo: 44,
    photoUrl: null,
    author: SampleAuthorElin,
    isSaved: false,
    ingredients: [
      { quantity: 1, unit: "", item: "Cauliflower" },
      { quantity: 150, unit: "g", item: "Mature cheddar" },
      { quantity: 100, unit: "g", item: "Bacon lardons" },
      { quantity: 500, unit: "ml", item: "Milk" },
      { quantity: 40, unit: "g", item: "Butter" },
    ],
    steps: [
      "Boil the florets 5 minutes, drain them very well.",
      "Make a thick cheese sauce, fold in the crisped lardons.",
      "Bake 25 minutes at 200C until it blisters on top.",
    ],
  },
];

/** The community tag catalogue offered by the "browse all tags" dialog. */
export const SampleTagCatalogue: RecipeTagCategory[] = [
  {
    group: "Diet",
    tags: [
      { name: "vegetarian", count: 2840 },
      { name: "vegan", count: 1310 },
      { name: "pescatarian", count: 420 },
      { name: "gluten-free", count: 760 },
      { name: "dairy-free", count: 530 },
      { name: "low-carb", count: 690 },
      { name: "high-protein", count: 980 },
    ],
  },
  {
    group: "Main ingredient",
    tags: [
      { name: "meat", count: 3100 },
      { name: "chicken", count: 2450 },
      { name: "beef", count: 1180 },
      { name: "pork", count: 860 },
      { name: "fish", count: 1520 },
      { name: "seafood", count: 640 },
      { name: "pasta", count: 1970 },
      { name: "rice", count: 1240 },
      { name: "beans", count: 580 },
      { name: "eggs", count: 700 },
    ],
  },
  {
    group: "Method",
    tags: [
      { name: "bbq", count: 1120 },
      { name: "oven", count: 1460 },
      { name: "one-pot", count: 1340 },
      { name: "sheet-pan", count: 720 },
      { name: "slow-cooker", count: 480 },
      { name: "air-fryer", count: 610 },
      { name: "no-cook", count: 250 },
    ],
  },
  {
    group: "Effort and cost",
    tags: [
      { name: "quick", count: 3600 },
      { name: "cheap", count: 2900 },
      { name: "expensive", count: 340 },
      { name: "batch-cook", count: 890 },
      { name: "freezer-friendly", count: 760 },
      { name: "leftovers", count: 540 },
      { name: "five-ingredient", count: 620 },
    ],
  },
  {
    group: "Mood",
    tags: [
      { name: "comfort", count: 2100 },
      { name: "light", count: 940 },
      { name: "spicy", count: 1280 },
      { name: "kid-friendly", count: 1560 },
      { name: "date-night", count: 380 },
      { name: "weeknight", count: 2700 },
      { name: "weekend", count: 610 },
    ],
  },
  {
    group: "Cuisine",
    tags: [
      { name: "italian", count: 1890 },
      { name: "mexican", count: 1420 },
      { name: "indian", count: 1350 },
      { name: "thai", count: 810 },
      { name: "japanese", count: 760 },
      { name: "nordic", count: 290 },
      { name: "middle-eastern", count: 680 },
    ],
  },
];

/** What a photo scan comes back with, used to demo the scan dialog. */
export const SampleScannedRecipe: ScannedRecipe = {
  title: "Tomato and bread soup",
  tags: ["vegetarian", "cheap", "comfort"],
  servings: 4,
  timeMinutes: 35,
  photoUrl: null,
  ingredients: [
    { quantity: 800, unit: "g", item: "Ripe tomatoes" },
    { quantity: 250, unit: "g", item: "Stale sourdough" },
    { quantity: 3, unit: "cloves", item: "Garlic" },
    { quantity: 4, unit: "tbsp", item: "Olive oil" },
    { quantity: 1, unit: "handful", item: "Basil" },
  ],
  steps: [
    "Warm the garlic in the oil until fragrant, not coloured.",
    "Add the tomatoes and cook down for fifteen minutes.",
    "Tear in the bread and stir until it collapses into the sauce.",
    "Rest off the heat, then finish with basil and more oil.",
  ],
};
