/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root/route'
import { Route as SplatRouteRouteImport } from './routes/$/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedIndexRouteRouteImport } from './routes/_authenticated/index/route'
import { Route as AuthenticatedPlanRouteRouteImport } from './routes/_authenticated/plan/route'
import { Route as AuthenticatedShoppingRouteRouteImport } from './routes/_authenticated/shopping/route'
import { Route as AuthenticatedWeekRouteRouteImport } from './routes/_authenticated/week/route'
import { Route as PublicForgotPasswordRouteRouteImport } from './routes/_public/forgot-password/route'
import { Route as PublicLoginRouteRouteImport } from './routes/_public/login/route'
import { Route as PublicSignUpRouteRouteImport } from './routes/_public/sign-up/route'
import { Route as AuthenticatedCommunityIndexRouteRouteImport } from './routes/_authenticated/community/index/route'
import { Route as AuthenticatedCommunityPersonIdRouteRouteImport } from './routes/_authenticated/community/$personId/route'
import { Route as AuthenticatedCommunityInboxRouteRouteImport } from './routes/_authenticated/community/inbox/route'
import { Route as AuthenticatedRecipesRecipeIdRouteRouteImport } from './routes/_authenticated/recipes/$recipeId/route'
import { Route as AuthenticatedRecipesEditRecipeIdRouteRouteImport } from './routes/_authenticated/recipes/edit/$recipeId/route'

const SplatRouteRoute = SplatRouteRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRouteRoute = AuthenticatedIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRouteRoute = AuthenticatedPlanRouteRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShoppingRouteRoute =
  AuthenticatedShoppingRouteRouteImport.update({
    id: '/shopping',
    path: '/shopping',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWeekRouteRoute = AuthenticatedWeekRouteRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicForgotPasswordRouteRoute =
  PublicForgotPasswordRouteRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicLoginRouteRoute = PublicLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSignUpRouteRoute = PublicSignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedCommunityIndexRouteRoute =
  AuthenticatedCommunityIndexRouteRouteImport.update({
    id: '/community/',
    path: '/community',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunityPersonIdRouteRoute =
  AuthenticatedCommunityPersonIdRouteRouteImport.update({
    id: '/community/$personId',
    path: '/community/$personId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunityInboxRouteRoute =
  AuthenticatedCommunityInboxRouteRouteImport.update({
    id: '/community/inbox',
    path: '/community/inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesRecipeIdRouteRoute =
  AuthenticatedRecipesRecipeIdRouteRouteImport.update({
    id: '/recipes/$recipeId',
    path: '/recipes/$recipeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesEditRecipeIdRouteRoute =
  AuthenticatedRecipesEditRecipeIdRouteRouteImport.update({
    id: '/recipes/edit/$recipeId',
    path: '/recipes/edit/$recipeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRouteRoute
  '/': typeof AuthenticatedIndexRouteRoute
  '/plan': typeof AuthenticatedPlanRouteRoute
  '/shopping': typeof AuthenticatedShoppingRouteRoute
  '/week': typeof AuthenticatedWeekRouteRoute
  '/forgot-password': typeof PublicForgotPasswordRouteRoute
  '/login': typeof PublicLoginRouteRoute
  '/sign-up': typeof PublicSignUpRouteRoute
  '/community/': typeof AuthenticatedCommunityIndexRouteRoute
  '/community/$personId': typeof AuthenticatedCommunityPersonIdRouteRoute
  '/community/inbox': typeof AuthenticatedCommunityInboxRouteRoute
  '/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRouteRoute
  '/recipes/edit/$recipeId': typeof AuthenticatedRecipesEditRecipeIdRouteRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRouteRoute
  '/': typeof AuthenticatedIndexRouteRoute
  '/plan': typeof AuthenticatedPlanRouteRoute
  '/shopping': typeof AuthenticatedShoppingRouteRoute
  '/week': typeof AuthenticatedWeekRouteRoute
  '/forgot-password': typeof PublicForgotPasswordRouteRoute
  '/login': typeof PublicLoginRouteRoute
  '/sign-up': typeof PublicSignUpRouteRoute
  '/community': typeof AuthenticatedCommunityIndexRouteRoute
  '/community/$personId': typeof AuthenticatedCommunityPersonIdRouteRoute
  '/community/inbox': typeof AuthenticatedCommunityInboxRouteRoute
  '/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRouteRoute
  '/recipes/edit/$recipeId': typeof AuthenticatedRecipesEditRecipeIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRouteRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRouteRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRouteRoute
  '/_authenticated/shopping': typeof AuthenticatedShoppingRouteRoute
  '/_authenticated/week': typeof AuthenticatedWeekRouteRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRouteRoute
  '/_public/login': typeof PublicLoginRouteRoute
  '/_public/sign-up': typeof PublicSignUpRouteRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRouteRoute
  '/_authenticated/community/$personId': typeof AuthenticatedCommunityPersonIdRouteRoute
  '/_authenticated/community/inbox': typeof AuthenticatedCommunityInboxRouteRoute
  '/_authenticated/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRouteRoute
  '/_authenticated/recipes/edit/$recipeId': typeof AuthenticatedRecipesEditRecipeIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/plan'
    | '/shopping'
    | '/week'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/community/'
    | '/community/$personId'
    | '/community/inbox'
    | '/recipes/$recipeId'
    | '/recipes/edit/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/plan'
    | '/shopping'
    | '/week'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/community'
    | '/community/$personId'
    | '/community/inbox'
    | '/recipes/$recipeId'
    | '/recipes/edit/$recipeId'
  id:
    | '__root__'
    | '/$'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/'
    | '/_authenticated/plan'
    | '/_authenticated/shopping'
    | '/_authenticated/week'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/sign-up'
    | '/_authenticated/community/'
    | '/_authenticated/community/$personId'
    | '/_authenticated/community/inbox'
    | '/_authenticated/recipes/$recipeId'
    | '/_authenticated/recipes/edit/$recipeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRouteRoute: typeof SplatRouteRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shopping': {
      id: '/_authenticated/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthenticatedShoppingRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/week': {
      id: '/_authenticated/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AuthenticatedWeekRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community/$personId': {
      id: '/_authenticated/community/$personId'
      path: '/community/$personId'
      fullPath: '/community/$personId'
      preLoaderRoute: typeof AuthenticatedCommunityPersonIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community/inbox': {
      id: '/_authenticated/community/inbox'
      path: '/community/inbox'
      fullPath: '/community/inbox'
      preLoaderRoute: typeof AuthenticatedCommunityInboxRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes/$recipeId': {
      id: '/_authenticated/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof AuthenticatedRecipesRecipeIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes/edit/$recipeId': {
      id: '/_authenticated/recipes/edit/$recipeId'
      path: '/recipes/edit/$recipeId'
      fullPath: '/recipes/edit/$recipeId'
      preLoaderRoute: typeof AuthenticatedRecipesEditRecipeIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRouteRoute: typeof AuthenticatedIndexRouteRoute
  AuthenticatedPlanRouteRoute: typeof AuthenticatedPlanRouteRoute
  AuthenticatedShoppingRouteRoute: typeof AuthenticatedShoppingRouteRoute
  AuthenticatedWeekRouteRoute: typeof AuthenticatedWeekRouteRoute
  AuthenticatedCommunityIndexRouteRoute: typeof AuthenticatedCommunityIndexRouteRoute
  AuthenticatedCommunityPersonIdRouteRoute: typeof AuthenticatedCommunityPersonIdRouteRoute
  AuthenticatedCommunityInboxRouteRoute: typeof AuthenticatedCommunityInboxRouteRoute
  AuthenticatedRecipesRecipeIdRouteRoute: typeof AuthenticatedRecipesRecipeIdRouteRoute
  AuthenticatedRecipesEditRecipeIdRouteRoute: typeof AuthenticatedRecipesEditRecipeIdRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRouteRoute: AuthenticatedIndexRouteRoute,
  AuthenticatedPlanRouteRoute: AuthenticatedPlanRouteRoute,
  AuthenticatedShoppingRouteRoute: AuthenticatedShoppingRouteRoute,
  AuthenticatedWeekRouteRoute: AuthenticatedWeekRouteRoute,
  AuthenticatedCommunityIndexRouteRoute: AuthenticatedCommunityIndexRouteRoute,
  AuthenticatedCommunityPersonIdRouteRoute:
    AuthenticatedCommunityPersonIdRouteRoute,
  AuthenticatedCommunityInboxRouteRoute: AuthenticatedCommunityInboxRouteRoute,
  AuthenticatedRecipesRecipeIdRouteRoute:
    AuthenticatedRecipesRecipeIdRouteRoute,
  AuthenticatedRecipesEditRecipeIdRouteRoute:
    AuthenticatedRecipesEditRecipeIdRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicForgotPasswordRouteRoute: typeof PublicForgotPasswordRouteRoute
  PublicLoginRouteRoute: typeof PublicLoginRouteRoute
  PublicSignUpRouteRoute: typeof PublicSignUpRouteRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicForgotPasswordRouteRoute: PublicForgotPasswordRouteRoute,
  PublicLoginRouteRoute: PublicLoginRouteRoute,
  PublicSignUpRouteRoute: PublicSignUpRouteRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRouteRoute: SplatRouteRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
